version: "3.7"
services:
  webmarketplace:
    restart: always
    build: .
    ports:
      - 3001:3000
    volumes:
      - ./abis:/my-project/.next/abis
    networks:
      - caddy

networks:
  caddy:
    external: true
